### ISSUE TITLE
It doesn't work on macOS.  

### ISSUE THREAD

**Issue by devxu** [BarbossHack/shmap#5]
It doesn't work on macOS.  
The SHM_DIR directory "/dev/shm" does not exist.

**Comment by BarbossHack** [comment]
Indeed, under MacOS there is no visible entry in the file system for the shared memory segments, so no /dev/shm (https://stackoverflow.com/a/73752984)

As a result, shmap does not support MacOS nor any BSD descendant.

I will update the README accordingly, thank you for your issue
